# Generated by Django 4.1.7 on 2023-06-26 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0008_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='product',
            new_name='produit',
        ),
    ]
