# Generated by Django 4.1.7 on 2023-04-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeLine', '0002_store_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(default=1, upload_to='store_profile/', verbose_name='Image for your store'),
            preserve_default=False,
        ),
    ]
