# Generated by Django 4.1.7 on 2023-04-11 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeLine', '0003_store_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='created_at',
        ),
    ]
