# Generated by Django 4.1.7 on 2023-05-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeLine', '0004_remove_store_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(upload_to='store_profile/%Y/%m/%d/', verbose_name='Image for your store'),
        ),
    ]
