products_api = [
    {
        'category':"Bracelets",
        'title':"Wave Decor Silver Bracelet",
        'image':'a1.jpg',
        'description':"Description",
        "price":930.00,
        "default_price":830,
        "start":"1",
    },
    {
        'category':"Watches",  
        'title':"Rhinestone Decor Round Pointer Quartz Watch",
        'image':'a2.jpg',
        'description':"Description",
        "price":980.00,
        "default_price":1030,
        "start":"3",
    },
    {
        'category':"Jwelery", 
        'title':"Rhinestone Decor Silver Wedding Band For Women Bridal Wedding Fine Jewelry",
        'image':'a3.jpg',
        'description':"Description",
        "price": 990.00,
        "default_price":999,
        "start":"4",     
    },
    {
        'category':"Jwelery", 
        'title':"1pc Simple & Elastic & Silver Ring With Shiny Bead For Mix & Match",
        'image':'a4.jpg',
        'description':"Description",
        "price": 330.00,
        "default_price":530,
        "start":"5", 
    },  
     {
        'category':"Jwelery", 
        'title':"1pc Vintage Green Dragonfly Ring 925 Sterling Silver Adjustable Finger Ring with Clear Cubic Zirconia Women Jewelry (packaged with box)",
        'image':'a5.jpg',
        'description':"Description",
        "price": 630.00,
        "default_price":1020,
        "start":"2",
    },  
    {
        'category':"Bracelets", 
        'title':"Infinity Symbol Decor Sterling Silver Chain Bracelet",
        'image':'a6.jpg',
        'description':"Description",
        "price": 730.00,
        "default_price":830,
        "start":"3",
    },
    {
        'category':"Bracelets", 
        'title':"1pc Shiny S925 Sterling Silver Heart Shape Full Diamond, Versatile, Fashionable & Luxury Chain Bracelet For Sum",
        'image':'a8.jpg',
        'description':"Description",
        "price": 330.00,
        "default_price":530,
        "start":"5",
    },
    {
        'category':"Bracelets", 
        'title':"1pc Fashionable Heart Decor Letter Detail Chain Bracelet For Women For Gift",
        'image':'a9.jpg',
        'description':"Description",
        "price": 630.00,
        "default_price":830,
        "start":"5",
    },
    {
        'category':"Watches", 
        'title':"1pc Men Women Silver Zinc Alloy Strap Business Round Dial Quartz Watch, For Daily Life",
        'image':'a10.jpg',
        'description':"Description",
        "price": 330.00,
        "default_price":700,
        "start":"4",
    },
    {
        'category':"Jwelery", 
        'title':"1pc Glamorous Pink Cubic Zirconia Heart Decor Sterling Silver Ring For Women For Wedding Party Jewelry Valentine's Day Gift",
        'image':'a11.jpg',
        'description':"Description",
        "price": 6.70,
        "default_price":10.30,
        "start":"5",
    },
    {
        'category':"Jwelery", 
        'title':"Rhinestone Decor Silver Wedding Band",
        'image':'a12.jpg',
        'description':"Description",
        "price": 33.00,
        "default_price":83.00,
        "start":"2",
    }, 
    {
        'category':"Bracelets", 
        'title':"Cubic Zirconia Bow Decor Sterling Silver Bracelet",
        'image':'a13.jpg',
        'description':"Description",
        "price": 310.00,
        "default_price":430,
        "start":"5",
    }, 
    {
        'category':"Earrings", 
        'title':"1pair Gorgeous Sparkle Earrings For Women s925 Sterling Silver Cubic Zirconia Flash Earrings Fine Jewelry Gift For Girls Prom Party Decor",
        'image':'a14.jpg',
        'description':"Description",
        "price": 330.00,
        "default_price":430,
        "start":"5",
    }, 
    {
        'category':"Watches", 
        'title':"Women's Watch Sets",
        'image':'a15.jpg',
        'description':"Description",
        "price": 330.00,
        "default_price":410,
        "start":"3",
    },
    {
        'category':"Watches", 
        'title':"1pc Women Silver Zinc Alloy Strap Fashion Round Dial Quartz Watch, For Daily Life",
        'image':'a16.jpg',
        'description':"Description",
        "price": 330.00,
        "default_price":500,
        "start":"2",
    }, 
    {
        'category':"Jwelery", 
        'title':"Heart Decor Cuff Silver Ring",
        'image':'a17.jpg',
        'description':"Description",
        "price": 330.00,
        "default_price":420,
        "start":"2",
    },
    {
        'category':"Bracelets", 
        'title':"1pc Fashionable Cubic Zirconia",
        'image':'a18.jpg',
        'description':"Description",
        "price": 10.00,
        "default_price":25,
        "start":"5",
    },
    {
        'category':"Jwelery", 
        'title':"1pc Cute Sterling Silver Two-tone Daisy Ring For Women, Suitable For Date And Party Gift In Summer",
        'image':'a19.jpg',
        'description':"Description",
        "price": 30.00,
        "default_price":50,
        "start":"4",
    },
    {
        'category':"Bracelets", 
        'title':"Bracelet",
        'image':'a20.jpg',
        'description':"Description",
        "price": 330.00,
        "default_price":430,
        "start":"5",
    },
    {
        'category':"Jwelery", 
        'title':"1pc Fashion Sterling Silver Infinity Symbol Detail Twist Ring For Women For Daily Decoration",
        'image':'a21.jpg',
        'description':"Description",
        "price": 330.00,
        "default_price":530,
        "start":"5",
    },
    {
        'category':"Watches", 
        'title':"Round Dial Pointer Silicone Watch",
        'image':'a22.jpg',
        'description':"Description",
        "price": 50.00,
        "default_price":80.00,
        "start":"5",
    },
    {
        'category':"Watches", 
        'title':"2 Pcs Women's Watch Sets",
        'image':'a23.jpg',
        'description':"Description",
        "price": 20.00,
        "default_price":30.00,
        "start":"3",
    },
]